[project]
name = "LeetCode"
description = "My LeetCode Solutions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
2877 = [
    "pandas>=2.3.3",
]
2878 = [
    "pandas>=2.3.3",
]
2879 = [
    "pandas>=2.3.3",
]
2880 = [
    "pandas>=2.3.3",
]
